---
title: "Data Interaction and Visualization 2027"
subtitle: |
  The 1^st^ Annual Chicagoland Data Interaction and Visualization Symposium

  Jan 4, 2027 at UIC
---

## What is DIV?

**DIV 2027** is a symposium for academic and industry researchers in the greater Chicago area working in fields related to **human--data interaction**. Our focus is the use of data representations such as visualization, language, and statistics to aid processing, understanding, and communicating data. Topics of interest include, but are not limited to:

- Data visualization
- Data storytelling and communication
- Data sonification
- Data accessibility
- Theories of data representation
- Scientific visualization
- Statistical graphics
- Tools for scientific computing
- Interfaces for data exploration and communication
- Artifical intelligence for data analysis systems

## Why DIV?

The goal of the workshop is to **promote connection and collaboration** amongst the local and regional community, and especially to **give graduate students and early researchers a venue to get feedback on their work** and to build their academic networks.

DIV was born from the recognition that Chicagoland is home to a wealth of researchers in human--data interaction and data visualization and that we all benefit from more regular connection across institutions. In 2025 a small gathering of visualization faculty and PhD students from Northwestern, U Chicago, and DePaul held a one-day retreat hosted by Northwestern's MU Collective. We had so much fun connecting that we did it again in 2026, adding in folks from UIC and Argonne, hosted at U Chicago's Data Science Institute. At that retreat we recognized the need for more opportunities like this: venues where students, faculty, and researchers can talk about ongoing work and get honest feedback. Venues where we can discuss hard topics, like where the field is, where it's going, and where it *should* be going. But also, importantly, venues where we can connect socially to local folks and build longer-lasting collaborations and friendships.

For 2027, we're expanding the topic from visualization to human--data interaction. We hope folks will join us and have fun making new connections and building new collaborations!

## Registration

In the first year, **registration will be handled by invitation from the organizers**. This is to manage capacity limits of the venue and to create an intentional gathering. We could easily have missed folks, so **if you or your students are interested**, please reach out to one of [the organizers](#organizers)!

We will use *Luma* for registration logistics, which manages invitations, and RSVPs through links sent via email. If you're planning on attending, please watch for emails through Luma.

## Posters

**All attendees** -- including faculty, researchers, postdocs, and students -- are invited to submit a poster for presentation at the workshop.

**Students are especially encouraged to submit**. We aim to provide a space for well-considered, thoughtful feedback on work of all stages, but especially unfinished or in-progress work that can most benefit from feedback and discussion.

### Submission

Submit a poster abstract using [this Google Form](https://docs.google.com/forms/d/e/1FAIpQLSc3QOOdpCsOQG7msMwVEiVWkohdU2Mk5HLLwnzaN6kzo8bIMQ/viewform?usp=header) by **November 30, 2026**.

Poster information:

- **Abstract length:** ≤ 250 words.
- **Suggested poster size:** 24 in × 36 in.
- **Lightning talk:** Poster presenters will give a **1 minute** lightning talk before the poster session to advertise their poster.
- **Work stage:** Posters may cover already-published work or work in progress.
- **Archivalness:** Posters and abstracts are non-archival.

## Location and schedule

DIV 2027 will be hosted at UIC's **[building info TBA]** on **Jan 4, 2027**.

The *tentative* schedule is as follows:

| Time | Activity |
|-----:|:------------------------------------------------|
| 8:30 | *Light breakfast & social* |
| 9:15 | **Intro and vision building** <br> From the organizers |
| 9:30 | **“Moonshot” talks** <br> 15-minute talk + 10-minute Q&A × 3 speakers <br> Topics and speakers TBA |
| 10:45 | *Break* |
| 11:00 | **Lightning talks** <br> 1-minute talks advertising posters |
| 11:30 | **Poster session** |
| 12:30 | *Lunch* |
| 1:30 | **Panel** <br> Topic and panelists TBA |
| 2:30 | *Break* |
| 2:45 | **Unconference idea selection** <br> Any attendee can propose a topic throughout the day, then all attendees select topics and split into groups by interest. |
| 3:00 | **Unconference mini-workshops** <br> As selected in the previous session. |
| 4:00 | **Reflections & ideas for next year** |
| 5:00 | *Social event nearby* |

## Organizers {#organizers}

- [Alex Kale](https://people.cs.uchicago.edu/~kalea/), University of Chicago (*Workshop Chair*)
- [Matthew Kay](https://www.mjskay.com/), Northwestern University
- Saeed Boorboor, University of Illinois at Chicago
- Michael Papka, Argonne National Laboratory
- Victor Mateevitsi, Argonne National Laboratory
- Joseph Insley, Argonne National Laboratory
